strava_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: strava_user
      password: strava_password
      port: 5432
      dbname: strava_raw
      schema: analytics
      threads: 4